### Create the appropriate environment with anaconda: conda env create -f environment.yml
### python=3.9.25, ipython=8.15


### This program aims at building a synthetic power spectrum in order to visualize in an easy way, using an échelle diagram, the effect of two physical parameters we are interested in: rotation and magnetic fields


import numpy as np
import pylab as plt
import csv
import os
import matplotlib as mpl



### Function plotting the synthetic power spectrum under including the effect of rotation and magnetic fields, under the form of an échelle diagram 

def plot_synthetic_echelle(nu0, Dpi1, tau_mod_0_rot, nu0_rot, tau_mod_plus_rot, nu_plus_rot, tau_mod_moins_rot, nu_moins_rot, tau_mod_0_mag, nu0_mag, tau_mod_plus_mag, nu_plus_mag, tau_mod_moins_mag, nu_moins_mag):

	## Parameters to scale the plot on the x-axis

	cc = 0.65
	tab_x = np.zeros((2))
	tab_x[0] = -1
	tab_x[1] = 1


	## Parameters to scale the plot on the y-axis

	tab_y = np.zeros((2))
	tab_y[0] = 61
	tab_y[1] = max(nu0)


	## Plot

	plt.figure(figsize=(6,8))
	plt.scatter(tau_mod_0_rot, nu0_rot, s=5, marker= 'o',  c='cornflowerblue', alpha=0.3, label='Component\nunaffected\nby rotation')
	plt.scatter(tau_mod_0_rot - Dpi1, nu0_rot, s=5, marker= 'o',  c='cornflowerblue', alpha=0.3)
	plt.scatter(tau_mod_plus_rot, nu_plus_rot, s=30, marker= '+',  c='r', alpha=0.3, label='1st\ncomponent\ngenerated\nby rotation')
	plt.scatter(tau_mod_plus_rot-Dpi1, nu_plus_rot, s=30, marker= '+',  c='r', alpha=0.3)
	plt.scatter(tau_mod_plus_rot-2*Dpi1, nu_plus_rot, s=30, marker= '+',  c='r', alpha=0.3)
	plt.scatter(tau_mod_moins_rot, nu_moins_rot, s=10, marker= 6,  c='g', alpha=0.3, label='2nd\ncomponent\ngenerated\nby rotation')
	plt.scatter(tau_mod_moins_rot-Dpi1, nu_moins_rot, s=10, marker= 6,  c='g', alpha=0.3)
	plt.scatter(tau_mod_moins_rot-2*Dpi1, nu_moins_rot, s=10, marker= 6,  c='g', alpha=0.3)
	plt.scatter(tau_mod_0_mag, nu0_mag, s=15, marker= 'o',  c='cornflowerblue', label='Addition of\nmagnetic\nfields')
	plt.scatter(tau_mod_0_mag - Dpi1, nu0_mag, s=15, marker= 'o',  c='cornflowerblue')
	plt.scatter(tau_mod_plus_mag, nu_plus_mag, s=50, marker= '+',  c='r', label='Addition of\nmagnetic\nfields')
	plt.scatter(tau_mod_plus_mag-Dpi1, nu_plus_mag, s=50, marker= '+',  c='r')
	plt.scatter(tau_mod_plus_mag-2*Dpi1, nu_plus_mag, s=50, marker= '+',  c='r')
	plt.scatter(tau_mod_moins_mag, nu_moins_mag, s=30, marker= 6,  c='g', label='Addition of\nmagnetic\nfields')
	plt.scatter(tau_mod_moins_mag-Dpi1, nu_moins_mag, s=30, marker= 6,  c='g')
	plt.scatter(tau_mod_moins_mag-2*Dpi1, nu_moins_mag, s=30, marker= 6,  c='g')
	plt.xlim(cc*tab_x*Dpi1)
	plt.ylim(tab_y)
	plt.legend(loc=2)
	plt.xlabel(r'$\tau$ mod $\Delta \Pi_{1}$', fontsize = 'x-large')
	plt.ylabel(r'$\nu$' + ' (' + r'$\mu$' + 'Hz)', fontsize = 'x-large')
	plt.title('Synthetic échelle diagram showing the\neffects of rotation and magnetic fields', fontsize = 'x-large')
	plt.savefig('./synthetic_echelle_dnurot_dnumag.pdf')
	plt.close()
	return



## Definition of parameters needed to construct the synthetic spectrum

Dpi1 = 80.
nu_max = 170.

n0 = 40
n = 200
nm = n0 + np.array(range(n))

P0 = nm * Dpi1					# building data points regularly in period
nu0 = 10**6 / P0				# obtaining the frequencies from the periods built

dnurot_test_all = np.array([500.]) * 10**(-9)	# parameter characterizing rotation


## Parameters characterizing magnetic fields

a_all = np.array([-0.49])
dnumag_test_all = np.array([100.]) * 10**(-9)


## Building the synthetic spectrum 

for i in range(dnurot_test_all.size):		# loop on the different rotation values
	dnurot_test = dnurot_test_all[i]
	for j in range(dnumag_test_all.size):	# loop on the values for the 1st parameter characterizing magnetic fields
		dnumag_test = dnumag_test_all[j]
		for k in range(a_all.size):	# loop on the values for the 2nd parameter characterizing magnetic fields
			a = a_all[k]


			## Including the effect of rotation on the frequencies: perturbation generating two additional frequencies all along the spectrum

			nu_plus_rot_ini = nu0 + dnurot_test * 10**6
			nu_moins_rot_ini = nu0 - dnurot_test * 10**6


			## Including the effect of magnetic fields on the frequencies: perturbation on the existing frequencies all along the spectrum, the original frequency
			## and the two additional frequencies generated by rotation

			nu0_mag_ini = nu0 + (1-a) * dnumag_test * 10.**6 * (nu_max / nu0)**3
			nu_plus_mag_ini = nu0 + dnurot_test * 10**6	+ (1+a/2) * dnumag_test * 10.**6 * (nu_max / nu0)**3
			nu_moins_mag_ini = nu0 - dnurot_test * 10**6 + (1+a/2) * dnumag_test * 10.**6 * (nu_max / nu0)**3


			## Obtaining the periods disturbed by rotation from the frequencies

			P0_rot_ini = 10**6 / nu0
			P_plus_rot_ini = 10**6 / nu_plus_rot_ini
			P_moins_rot_ini = 10**6 / nu_moins_rot_ini


			## Obtaining the periods disturbed by magnetic fields from the frequencies

			P0_mag_ini = 10**6 / nu0_mag_ini
			P_plus_mag_ini = 10**6 / nu_plus_mag_ini
			P_moins_mag_ini = 10**6 / nu_moins_mag_ini


			## Obtaining the stretched-period spacing disturbed by rotation from the frequencies

			dtau_0_rot = np.zeros(P0.size)
			dtau_0_rot[:]= Dpi1
			dtau_plus_rot = Dpi1 / (1 + dnurot_test / (10**(-6) * nu0))**2
			dtau_moins_rot = Dpi1 / (1 - dnurot_test / (10**(-6) * nu0))**2
			
			
			## Obtaining the stretched-period spacing disturbed by magnetic fields from the frequencies

			dtau_0_mag = Dpi1 / (1 + (1-a) * dnumag_test / (10**(-6) * nu0)**4 * (10**(-6) * nu_max)**3)**2
			dtau_plus_mag = Dpi1 / (1 + dnurot_test / (10**(-6) * nu0) + (1. + a/2) * dnumag_test / (10**(-6) * nu0)**4 * (10**(-6) * nu_max)**3)**2
			dtau_moins_mag = Dpi1 / (1 - dnurot_test / (10**(-6) * nu0) + (1. + a/2) * dnumag_test / (10**(-6) * nu0)**4 * (10**(-6) * nu_max)**3)**2


			## Building the stretched periods disturbed by rotation and magnetic fields, respectively, from the stretched-period spacing

			P_plus_rot = np.zeros(P_plus_rot_ini.size)		# effect of rotation
			P_moins_rot = np.zeros(P_moins_rot_ini.size)
			P0_rot = np.zeros(P0_rot_ini.size)
			P_plus_rot[:] = P_plus_rot_ini
			P_moins_rot[:] = P_moins_rot_ini
			P0_rot[:] = P0_rot_ini

			
			P_plus_mag = np.zeros(P_plus_mag_ini.size)		# effect of magnetic fields
			P_moins_mag = np.zeros(P_moins_mag_ini.size)
			P0_mag = np.zeros(P0_mag_ini.size)
			P_plus_mag[:] = P_plus_mag_ini
			P_moins_mag[:] = P_moins_mag_ini
			P0_mag[:] = P0_mag_ini

			for j in range(1,n):
				P_plus_rot[j] = P_plus_rot[j-1] + dtau_plus_rot[j]	# effect of rotation
				P_moins_rot[j] = P_moins_rot[j-1] + dtau_moins_rot[j]
				P0_rot[j] = P0_rot[j-1] + dtau_0_rot[j]

				P_plus_mag[j] = P_plus_mag[j-1] + dtau_plus_mag[j]	# effect of magnetic fields
				P_moins_mag[j] = P_moins_mag[j-1] + dtau_moins_mag[j]
				P0_mag[j] = P0_mag[j-1] + dtau_0_mag[j]


			## Obtaining the final frequencies disturbed by rotation from the stretched periods

			nu_plus_rot = 10**6 / P_plus_rot
			nu_moins_rot = 10**6/ P_moins_rot
			nu0_rot = 10**6/ P0_rot
			
			
			## Obtaining the final frequencies disturbed by magnetic fields from the stretched periods

			nu_plus_mag = 10**6 / P_plus_mag
			nu_moins_mag = 10**6/ P_moins_mag
			nu0_mag = 10**6/ P0_mag


			## Folding the stretched periods disturbed by rotation over a constant period spacing
			
			tau_mod_plus_rot = P_plus_rot % Dpi1
			tau_mod_moins_rot = P_moins_rot % Dpi1
			tau_mod_0_rot = P0_rot % Dpi1


			## Folding the stretched periods disturbed by magnetic fields over a constant period spacing

			tau_mod_plus_mag = P_plus_mag % Dpi1
			tau_mod_moins_mag = P_moins_mag % Dpi1
			tau_mod_0_mag = P0_mag % Dpi1



			## Plot

			plot_synthetic_echelle(nu0, Dpi1, tau_mod_0_rot, nu0_rot, tau_mod_plus_rot, nu_plus_rot, tau_mod_moins_rot, nu_moins_rot, tau_mod_0_mag, nu0_mag, tau_mod_plus_mag, nu_plus_mag, tau_mod_moins_mag, nu_moins_mag)


